import React, { useState } from "react";
import {
  AiFillStar,
  AiOutlineStar,
  AiOutlineLike,
  AiFillLike,
} from "react-icons/ai";
import { FaFacebookF } from "react-icons/fa";
import { motion, AnimatePresence } from "framer-motion";

// Sample reviews data (aap apne hisaab se badal sakte hain)
const initialReviews = [
   {
    id: 1,
    user: "Sarah K.",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    rating: 4.5,
    date: "July 12, 2025",
    text: "Absolutely love these earbuds! The sound quality is incredible and they fit perfectly. Battery life lasts all day.",
    likes: 12,
    likedByUser: false,
    replies: [
      {
        id: 101,
        user: "Mike D.",
        avatar: "https://randomuser.me/api/portraits/men/75.jpg",
        date: "July 13, 2025",
        text: "Agreed! They are fantastic for workouts.",
        likes: 4,
        likedByUser: false,
      },
    ],
  },
  {
    id: 2,
    user: "James L.",
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    rating: 4,
    date: "July 10, 2025",
    text: "Great wireless earbuds with solid connectivity. Wish the case was a bit smaller, but overall very happy.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 3,
    user: "Emily R.",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    rating: 5,
    date: "July 8, 2025",
    text: "Best earbuds I've ever owned! Noise cancellation is top notch and controls are intuitive.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 4,
    user: "David S.",
    avatar: "https://randomuser.me/api/portraits/men/30.jpg",
    rating: 3.5,
    date: "July 5, 2025",
    text: "Good sound quality but they sometimes lose connection if I move too far from my phone.",
    likes: 5,
    likedByUser: false,
    replies: [
      {
        id: 102,
        user: "Lisa M.",
        avatar: "https://randomuser.me/api/portraits/women/45.jpg",
        date: "July 6, 2025",
        text: "Try resetting them; it helped me a lot.",
        likes: 2,
        likedByUser: false,
      },
    ],
  },
  {
    id: 5,
    user: "Nina W.",
    avatar: "https://randomuser.me/api/portraits/women/52.jpg",
    rating: 4,
    date: "July 3, 2025",
    text: "Comfortable fit and good battery life. The app could use some improvements.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 6,
    user: "Mark T.",
    avatar: "https://randomuser.me/api/portraits/men/62.jpg",
    rating: 5,
    date: "July 1, 2025",
    text: "Exceeded my expectations. Clear calls and deep bass.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 7,
    user: "Olivia G.",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    rating: 4.5,
    date: "June 29, 2025",
    text: "Sleek design and easy to use. The controls respond instantly.",
    likes: 11,
    likedByUser: false,
    replies: [
      {
        id: 103,
        user: "Ethan B.",
        avatar: "https://randomuser.me/api/portraits/men/50.jpg",
        date: "June 30, 2025",
        text: "Same here! Loving these earbuds so far.",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 8,
    user: "Sophia L.",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    rating: 5,
    date: "June 27, 2025",
    text: "Battery life is outstanding! I use them all day without charging.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 9,
    user: "Liam H.",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    rating: 4.5,
    date: "June 25, 2025",
    text: "Sound clarity is impressive and the design is sleek. Battery lasts well during long commutes.",
    likes: 10,
    likedByUser: false,
    replies: [
      {
        id: 104,
        user: "Mia S.",
        avatar: "https://randomuser.me/api/portraits/women/33.jpg",
        date: "June 26, 2025",
        text: "Completely agree with you! The battery life is a game changer.",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 10,
    user: "Noah W.",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    rating: 3.5,
    date: "June 23, 2025",
    text: "Good earbuds but sometimes the Bluetooth connection drops in crowded places.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 11,
    user: "Ava J.",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    rating: 5,
    date: "June 20, 2025",
    text: "Exceptional noise cancellation and comfortable fit. Worth every penny!",
    likes: 25,
    likedByUser: false,
    replies: [
      {
        id: 105,
        user: "Ethan R.",
        avatar: "https://randomuser.me/api/portraits/men/44.jpg",
        date: "June 21, 2025",
        text: "Thanks for the recommendation! Just bought mine.",
        likes: 5,
        likedByUser: false,
      },
    ],
  },
  {
    id: 12,
    user: "Sophia B.",
    avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    rating: 4,
    date: "June 18, 2025",
    text: "Good sound quality, but the touch controls can be a bit sensitive sometimes.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 13,
    user: "Mason K.",
    avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    rating: 4.8,
    date: "June 15, 2025",
    text: "Love the bass and overall sound balance. Battery life exceeds expectations.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 14,
    user: "Isabella T.",
    avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    rating: 3.8,
    date: "June 13, 2025",
    text: "The earbuds are good but a bit pricey for the features offered.",
    likes: 4,
    likedByUser: false,
    replies: [
      {
        id: 106,
        user: "Lucas M.",
        avatar: "https://randomuser.me/api/portraits/men/29.jpg",
        date: "June 14, 2025",
        text: "I think the quality justifies the price.",
        likes: 2,
        likedByUser: false,
      },
    ],
  },
  {
    id: 15,
    user: "Charlotte N.",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    rating: 5,
    date: "June 11, 2025",
    text: "These are the best earbuds I've tried! Crystal clear calls and great music experience.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 16,
    user: "Benjamin G.",
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    rating: 4,
    date: "June 9, 2025",
    text: "Decent earbuds for daily use. Could improve on battery life though.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 17,
    user: "Amelia F.",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    rating: 4.7,
    date: "June 7, 2025",
    text: "Lightweight and comfortable, perfect for workouts and daily commute.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 18,
    user: "Elijah C.",
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    rating: 3.9,
    date: "June 5, 2025",
    text: "Good sound but wish the earbuds had more customizable settings.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 19,
    user: "Mia P.",
    avatar: "https://randomuser.me/api/portraits/women/48.jpg",
    rating: 5,
    date: "June 3, 2025",
    text: "Outstanding battery life and amazing sound quality. Highly recommended!",
    likes: 30,
    likedByUser: false,
    replies: [
      {
        id: 107,
        user: "Oliver S.",
        avatar: "https://randomuser.me/api/portraits/men/27.jpg",
        date: "June 4, 2025",
        text: "Glad you mentioned the battery life! Just what I needed.",
        likes: 7,
        likedByUser: false,
      },
    ],
  },
  {
    id: 20,
    user: "Logan J.",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    rating: 4.2,
    date: "June 1, 2025",
    text: "Good fit and sound quality. Controls sometimes don't register my taps correctly.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 21,
    user: "Ella V.",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    rating: 4.6,
    date: "May 30, 2025",
    text: "Love the design and how easy it is to connect to multiple devices.",
    likes: 13,
    likedByUser: false,
    replies: [
      {
        id: 108,
        user: "Jacob K.",
        avatar: "https://randomuser.me/api/portraits/men/39.jpg",
        date: "May 31, 2025",
        text: "Connection stability is impressive, agreed!",
        likes: 4,
        likedByUser: false,
      },
    ],
  },
  {
    id: 22,
    user: "Harper W.",
    avatar: "https://randomuser.me/api/portraits/women/60.jpg",
    rating: 4.1,
    date: "May 28, 2025",
    text: "Great earbuds for the price. Would like better app integration though.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 23,
    user: "James P.",
    avatar: "https://randomuser.me/api/portraits/men/59.jpg",
    rating: 4.8,
    date: "May 25, 2025",
    text: "Superb soundstage and very comfortable. Battery life is solid as well.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 24,
    user: "Zoe M.",
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    rating: 3.7,
    date: "May 22, 2025",
    text: "Sound quality is good but the touch controls can be frustrating sometimes.",
    likes: 5,
    likedByUser: false,
    replies: [
      {
        id: 109,
        user: "Landon R.",
        avatar: "https://randomuser.me/api/portraits/men/61.jpg",
        date: "May 23, 2025",
        text: "Try disabling some gesture controls in the app; that helped me.",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 25,
    user: "Victoria T.",
    avatar: "https://randomuser.me/api/portraits/women/49.jpg",
    rating: 5,
    date: "May 20, 2025",
    text: "Amazing earbuds! Great sound and the case is compact and easy to carry.",
    likes: 28,
    likedByUser: false,
    replies: [],
  },
  {
    id: 26,
    user: "Henry G.",
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    rating: 4.3,
    date: "May 18, 2025",
    text: "Very good earbuds overall. Comfortable fit and excellent sound clarity.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 27,
    user: "Grace D.",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    rating: 4.7,
    date: "May 15, 2025",
    text: "I love the sleek design and the quick pairing feature.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 28,
    user: "Alexander F.",
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    rating: 3.9,
    date: "May 13, 2025",
    text: "Good sound but battery life could be better.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 29,
    user: "Chloe S.",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    rating: 4.9,
    date: "May 10, 2025",
    text: "The noise cancellation feature is excellent. Very happy with the purchase.",
    likes: 26,
    likedByUser: false,
    replies: [
      {
        id: 110,
        user: "Sebastian J.",
        avatar: "https://randomuser.me/api/portraits/men/34.jpg",
        date: "May 11, 2025",
        text: "I totally agree, noise cancellation is impressive for this price range.",
        likes: 9,
        likedByUser: false,
      },
    ],
  },
  {
    id: 30,
    user: "Ella C.",
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    rating: 4.2,
    date: "May 8, 2025",
    text: "Very comfortable to wear and great sound quality. Would buy again.",
    likes: 13,
    likedByUser: false,
    replies: [],
  },
  {
    id: 31,
    user: "Daniel N.",
    avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    rating: 4.4,
    date: "May 6, 2025",
    text: "Solid earbuds with reliable Bluetooth connectivity and clear sound.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 32,
    user: "Lily O.",
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    rating: 4.8,
    date: "May 4, 2025",
    text: "Amazing battery life and the app features are really helpful.",
    likes: 20,
    likedByUser: false,
    replies: [
      {
        id: 111,
        user: "Matthew P.",
        avatar: "https://randomuser.me/api/portraits/men/36.jpg",
        date: "May 5, 2025",
        text: "Thanks for the heads up about the app, I'll check it out.",
        likes: 5,
        likedByUser: false,
      },
    ],
  },
  {
    id: 33,
    user: "Samuel Q.",
    avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    rating: 4,
    date: "May 2, 2025",
    text: "Good earbuds for casual listening but sometimes the connection lags.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 34,
    user: "Ella R.",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    rating: 5,
    date: "April 30, 2025",
    text: "Best purchase I've made this year! Sound and comfort are amazing.",
    likes: 24,
    likedByUser: false,
    replies: [],
  },
  {
    id: 35,
    user: "Jackson S.",
    avatar: "https://randomuser.me/api/portraits/men/38.jpg",
    rating: 3.6,
    date: "April 28, 2025",
    text: "Decent earbuds but expected more from noise cancellation.",
    likes: 5,
    likedByUser: false,
    replies: [
      {
        id: 112,
        user: "Avery V.",
        avatar: "https://randomuser.me/api/portraits/women/40.jpg",
        date: "April 29, 2025",
        text: "Same here, I use them mostly for calls rather than music.",
        likes: 2,
        likedByUser: false,
      },
    ],
  },
  {
    id: 36,
    user: "Victoria W.",
    avatar: "https://randomuser.me/api/portraits/women/50.jpg",
    rating: 4.5,
    date: "April 26, 2025",
    text: "Great earbuds for the price, comfortable fit and good sound balance.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 37,
    user: "Owen T.",
    avatar: "https://randomuser.me/api/portraits/men/40.jpg",
    rating: 4.3,
    date: "April 24, 2025",
    text: "Solid build quality and excellent call clarity.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 38,
    user: "Zara Y.",
    avatar: "https://randomuser.me/api/portraits/women/54.jpg",
    rating: 5,
    date: "April 22, 2025",
    text: "Fantastic earbuds! The sound quality is crisp and the fit is secure.",
    likes: 27,
    likedByUser: false,
    replies: [],
  },
  {
    id: 39,
    user: "Nathan L.",
    avatar: "https://randomuser.me/api/portraits/men/53.jpg",
    rating: 3.8,
    date: "April 20, 2025",
    text: "Good for the price but battery life could be longer.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 40,
    user: "Luna M.",
    avatar: "https://randomuser.me/api/portraits/women/56.jpg",
    rating: 4.9,
    date: "April 18, 2025",
    text: "Excellent sound and very comfortable to wear for hours.",
    likes: 23,
    likedByUser: false,
    replies: [],
  },
  {
    id: 41,
    user: "Jack R.",
    avatar: "https://randomuser.me/api/portraits/men/58.jpg",
    rating: 4.1,
    date: "April 16, 2025",
    text: "Good earbuds but touch controls sometimes don’t work as expected.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 42,
    user: "Nora S.",
    avatar: "https://randomuser.me/api/portraits/women/59.jpg",
    rating: 5,
    date: "April 14, 2025",
    text: "Love these earbuds! They have exceeded my expectations in every way.",
    likes: 30,
    likedByUser: false,
    replies: [
      {
        id: 113,
        user: "Henry D.",
        avatar: "https://randomuser.me/api/portraits/men/54.jpg",
        date: "April 15, 2025",
        text: "Agreed! Best earbuds I've had in years.",
        likes: 8,
        likedByUser: false,
      },
    ],
  },
  {
    id: 43,
    user: "Scarlett C.",
    avatar: "https://randomuser.me/api/portraits/women/61.jpg",
    rating: 4.4,
    date: "April 12, 2025",
    text: "Very good earbuds, comfortable and clear sound quality.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 44,
    user: "Leo K.",
    avatar: "https://randomuser.me/api/portraits/men/57.jpg",
    rating: 4.6,
    date: "April 10, 2025",
    text: "Great fit and easy to use. The case is a bit bulky though.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 45,
    user: "Camila F.",
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    rating: 3.9,
    date: "April 8, 2025",
    text: "Sound is good but had some issues with Bluetooth pairing at first.",
    likes: 5,
    likedByUser: false,
    replies: [
      {
        id: 114,
        user: "Isaac H.",
        avatar: "https://randomuser.me/api/portraits/men/63.jpg",
        date: "April 9, 2025",
        text: "Try resetting the earbuds; that fixed it for me.",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 46,
    user: "Layla P.",
    avatar: "https://randomuser.me/api/portraits/women/64.jpg",
    rating: 4.8,
    date: "April 6, 2025",
    text: "Excellent battery life and great sound. Very happy with this purchase.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 47,
    user: "Maverick G.",
    avatar: "https://randomuser.me/api/portraits/men/64.jpg",
    rating: 4.2,
    date: "April 4, 2025",
    text: "Good earbuds overall. Controls can be a bit tricky sometimes.",
    likes: 10,
    likedByUser: false,
    replies: [],
  },
  {
    id: 48,
    user: "Hannah T.",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    rating: 5,
    date: "April 2, 2025",
    text: "Perfect earbuds for my daily commute and workouts. Highly recommended!",
    likes: 29,
    likedByUser: false,
    replies: [],
  },
  {
    id: 49,
    user: "Carter J.",
    avatar: "https://randomuser.me/api/portraits/men/65.jpg",
    rating: 3.7,
    date: "April 1, 2025",
    text: "Sound quality is decent but I wish the touch controls were more responsive.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 50,
    user: "Aria V.",
    avatar: "https://randomuser.me/api/portraits/women/66.jpg",
    rating: 4.9,
    date: "March 30, 2025",
    text: "Amazing sound, battery life, and comfortable fit. Exceeded all expectations!",
    likes: 31,
    likedByUser: false,
    replies: [
      {
        id: 115,
        user: "James W.",
        avatar: "https://randomuser.me/api/portraits/men/66.jpg",
        date: "March 31, 2025",
        text: "Thanks for sharing! Just ordered mine.",
        likes: 6,
        likedByUser: false,
      },
    ],
  },
  {
    id: 51,
    user: "Evelyn M.",
    avatar: "https://randomuser.me/api/portraits/women/67.jpg",
    rating: 4.3,
    date: "March 28, 2025",
    text: "Good earbuds with nice sound quality. The case could be smaller.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 52,
    user: "Wyatt L.",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    rating: 4.5,
    date: "March 26, 2025",
    text: "Excellent earbuds with solid build quality and sound clarity.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 53,
    user: "Ella P.",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    rating: 4.7,
    date: "March 24, 2025",
    text: "Very comfortable and sound quality is great. Battery lasts all day.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 54,
    user: "Sebastian D.",
    avatar: "https://randomuser.me/api/portraits/men/68.jpg",
    rating: 4.1,
    date: "March 22, 2025",
    text: "Good earbuds but sometimes the connection is spotty.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 55,
    user: "Madison K.",
    avatar: "https://randomuser.me/api/portraits/women/69.jpg",
    rating: 5,
    date: "March 20, 2025",
    text: "Love these earbuds! Great sound, comfortable fit and long battery life.",
    likes: 32,
    likedByUser: false,
    replies: [],
  },
  {
    id: 56,
    user: "Oliver V.",
    avatar: "https://randomuser.me/api/portraits/men/69.jpg",
    rating: 3.9,
    date: "March 18, 2025",
    text: "Good sound but controls can be a little unresponsive sometimes.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 57,
    user: "Sofia M.",
    avatar: "https://randomuser.me/api/portraits/women/70.jpg",
    rating: 4.6,
    date: "March 16, 2025",
    text: "Great earbuds for workouts and daily use. Battery lasts long.",
    likes: 18,
    likedByUser: false,
    replies: [
      {
        id: 116,
        user: "Mason R.",
        avatar: "https://randomuser.me/api/portraits/men/70.jpg",
        date: "March 17, 2025",
        text: "Agreed! Perfect for gym sessions.",
        likes: 5,
        likedByUser: false,
      },
    ],
  },
  {
    id: 58,
    user: "Henry N.",
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    rating: 4,
    date: "March 14, 2025",
    text: "Good earbuds for the price. Sound quality is decent.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 59,
    user: "Ella M.",
    avatar: "https://randomuser.me/api/portraits/women/71.jpg",
    rating: 4.7,
    date: "March 12, 2025",
    text: "Really impressed by the clarity and bass. Perfect for both music and podcasts.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 60,
    user: "Jackson B.",
    avatar: "https://randomuser.me/api/portraits/men/72.jpg",
    rating: 4.2,
    date: "March 10, 2025",
    text: "Comfortable fit but sometimes one earbud disconnects randomly.",
    likes: 7,
    likedByUser: false,
    replies: [
      {
        id: 117,
        user: "Grace H.",
        avatar: "https://randomuser.me/api/portraits/women/72.jpg",
        date: "March 11, 2025",
        text: "Try resetting the earbuds and reconnecting, worked for me!",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 61,
    user: "Lucas F.",
    avatar: "https://randomuser.me/api/portraits/men/73.jpg",
    rating: 5,
    date: "March 8, 2025",
    text: "Superb sound quality and amazing battery life. Highly recommend these earbuds.",
    likes: 28,
    likedByUser: false,
    replies: [],
  },
  {
    id: 62,
    user: "Amelia R.",
    avatar: "https://randomuser.me/api/portraits/women/73.jpg",
    rating: 3.9,
    date: "March 6, 2025",
    text: "Sound quality is good but controls are sometimes laggy.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 63,
    user: "Mason D.",
    avatar: "https://randomuser.me/api/portraits/men/74.jpg",
    rating: 4.5,
    date: "March 4, 2025",
    text: "Very comfortable and stable fit during running and workouts.",
    likes: 15,
    likedByUser: false,
    replies: [
      {
        id: 118,
        user: "Olivia K.",
        avatar: "https://randomuser.me/api/portraits/women/74.jpg",
        date: "March 5, 2025",
        text: "I use these for jogging too, they don't fall out easily!",
        likes: 4,
        likedByUser: false,
      },
    ],
  },
  {
    id: 64,
    user: "Ethan M.",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    rating: 4.8,
    date: "March 2, 2025",
    text: "Excellent soundstage and very intuitive touch controls.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 65,
    user: "Sophia N.",
    avatar: "https://randomuser.me/api/portraits/women/75.jpg",
    rating: 4.1,
    date: "February 28, 2025",
    text: "Good earbuds overall but charging case could be improved.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 66,
    user: "Liam G.",
    avatar: "https://randomuser.me/api/portraits/men/76.jpg",
    rating: 4.3,
    date: "February 26, 2025",
    text: "Battery lasts longer than expected. Great value for the price.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 67,
    user: "Isabella J.",
    avatar: "https://randomuser.me/api/portraits/women/76.jpg",
    rating: 5,
    date: "February 24, 2025",
    text: "Noise cancellation works perfectly. I can focus even in noisy environments.",
    likes: 29,
    likedByUser: false,
    replies: [
      {
        id: 119,
        user: "Jack T.",
        avatar: "https://randomuser.me/api/portraits/men/77.jpg",
        date: "February 25, 2025",
        text: "Totally agree! They help me concentrate during work.",
        likes: 7,
        likedByUser: false,
      },
    ],
  },
  {
    id: 68,
    user: "Mia C.",
    avatar: "https://randomuser.me/api/portraits/women/77.jpg",
    rating: 4.0,
    date: "February 22, 2025",
    text: "Comfortable but wish the earbuds were a bit lighter.",
    likes: 5,
    likedByUser: false,
    replies: [],
  },
  {
    id: 69,
    user: "Noah E.",
    avatar: "https://randomuser.me/api/portraits/men/78.jpg",
    rating: 3.8,
    date: "February 20, 2025",
    text: "Good sound but the touch controls are sometimes unresponsive.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 70,
    user: "Charlotte W.",
    avatar: "https://randomuser.me/api/portraits/women/78.jpg",
    rating: 4.9,
    date: "February 18, 2025",
    text: "These earbuds are amazing! I love how crisp the audio is and the fit is perfect.",
    likes: 26,
    likedByUser: false,
    replies: [],
  },
  {
    id: 71,
    user: "Oliver S.",
    avatar: "https://randomuser.me/api/portraits/men/79.jpg",
    rating: 4.4,
    date: "February 16, 2025",
    text: "Great earbuds with stable connection and good sound quality.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 72,
    user: "Amelia P.",
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    rating: 4.6,
    date: "February 14, 2025",
    text: "Battery life is excellent. I get almost two full days of use.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 73,
    user: "Henry L.",
    avatar: "https://randomuser.me/api/portraits/men/80.jpg",
    rating: 3.7,
    date: "February 12, 2025",
    text: "The earbuds are decent but the case feels bulky in my pocket.",
    likes: 7,
    likedByUser: false,
    replies: [
      {
        id: 120,
        user: "Ella B.",
        avatar: "https://randomuser.me/api/portraits/women/80.jpg",
        date: "February 13, 2025",
        text: "I agree, case size is a bit large but performance makes up for it.",
        likes: 3,
        likedByUser: false,
      },
    ],
  },
  {
    id: 74,
    user: "Logan M.",
    avatar: "https://randomuser.me/api/portraits/men/81.jpg",
    rating: 4.8,
    date: "February 10, 2025",
    text: "Fantastic earbuds! Sound quality, battery life, and fit are all top-notch.",
    likes: 25,
    likedByUser: false,
    replies: [],
  },
  {
    id: 75,
    user: "Grace A.",
    avatar: "https://randomuser.me/api/portraits/women/81.jpg",
    rating: 4.3,
    date: "February 8, 2025",
    text: "Love the design and ease of use. Controls are mostly responsive.",
    likes: 13,
    likedByUser: false,
    replies: [],
  },
  {
    id: 76,
    user: "Benjamin N.",
    avatar: "https://randomuser.me/api/portraits/men/82.jpg",
    rating: 4.0,
    date: "February 6, 2025",
    text: "Good sound and comfortable fit but would like a longer cable for charging.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 77,
    user: "Zoe H.",
    avatar: "https://randomuser.me/api/portraits/women/82.jpg",
    rating: 5,
    date: "February 4, 2025",
    text: "Excellent earbuds! They block outside noise really well.",
    likes: 31,
    likedByUser: false,
    replies: [],
  },
  {
    id: 78,
    user: "Jacob V.",
    avatar: "https://randomuser.me/api/portraits/men/83.jpg",
    rating: 3.9,
    date: "February 2, 2025",
    text: "Decent earbuds but charging case takes longer than expected.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 79,
    user: "Hannah J.",
    avatar: "https://randomuser.me/api/portraits/women/83.jpg",
    rating: 4.7,
    date: "January 31, 2025",
    text: "Very comfortable and battery lasts longer than I expected.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 80,
    user: "Sebastian R.",
    avatar: "https://randomuser.me/api/portraits/men/84.jpg",
    rating: 4.5,
    date: "January 29, 2025",
    text: "Great value for money. Sound quality is clear and bass is deep.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 81,
    user: "Lily M.",
    avatar: "https://randomuser.me/api/portraits/women/84.jpg",
    rating: 4.2,
    date: "January 27, 2025",
    text: "I love the touch controls but sometimes they can be a bit sensitive.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 82,
    user: "Owen B.",
    avatar: "https://randomuser.me/api/portraits/men/85.jpg",
    rating: 3.8,
    date: "January 25, 2025",
    text: "Good earbuds but the Bluetooth range is shorter than I expected.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 83,
    user: "Ella T.",
    avatar: "https://randomuser.me/api/portraits/women/85.jpg",
    rating: 5,
    date: "January 23, 2025",
    text: "Best earbuds I've owned! The sound and comfort are unmatched.",
    likes: 29,
    likedByUser: false,
    replies: [],
  },
  {
    id: 84,
    user: "Elijah P.",
    avatar: "https://randomuser.me/api/portraits/men/86.jpg",
    rating: 4.4,
    date: "January 21, 2025",
    text: "Very good earbuds with reliable connectivity and clear audio.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 85,
    user: "Mia V.",
    avatar: "https://randomuser.me/api/portraits/women/86.jpg",
    rating: 4.9,
    date: "January 19, 2025",
    text: "Amazing earbuds! The battery lasts long and sound is clear.",
    likes: 33,
    likedByUser: false,
    replies: [],
  },
  {
    id: 86,
    user: "Jacob S.",
    avatar: "https://randomuser.me/api/portraits/men/87.jpg",
    rating: 4.1,
    date: "January 17, 2025",
    text: "Comfortable fit and good sound but touch controls can be tricky.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 87,
    user: "Amelia B.",
    avatar: "https://randomuser.me/api/portraits/women/87.jpg",
    rating: 4.6,
    date: "January 15, 2025",
    text: "Love these earbuds! Perfect for workouts and daily use.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 88,
    user: "Daniel H.",
    avatar: "https://randomuser.me/api/portraits/men/88.jpg",
    rating: 3.9,
    date: "January 13, 2025",
    text: "Good earbuds but expected better noise cancellation.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 89,
    user: "Sophia T.",
    avatar: "https://randomuser.me/api/portraits/women/88.jpg",
    rating: 5,
    date: "January 11, 2025",
    text: "These earbuds are fantastic! Crystal clear sound and comfy fit.",
    likes: 31,
    likedByUser: false,
    replies: [],
  },
  {
    id: 90,
    user: "Mason L.",
    avatar: "https://randomuser.me/api/portraits/men/89.jpg",
    rating: 4.3,
    date: "January 9, 2025",
    text: "Good quality earbuds, the battery life is very impressive.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 91,
    user: "Isabella Q.",
    avatar: "https://randomuser.me/api/portraits/women/89.jpg",
    rating: 4.7,
    date: "January 7, 2025",
    text: "I really like the noise cancelling feature and the design is sleek.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 92,
    user: "Logan R.",
    avatar: "https://randomuser.me/api/portraits/men/90.jpg",
    rating: 3.8,
    date: "January 5, 2025",
    text: "Decent earbuds but the Bluetooth sometimes disconnects unexpectedly.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 93,
    user: "Ella Z.",
    avatar: "https://randomuser.me/api/portraits/women/90.jpg",
    rating: 5,
    date: "January 3, 2025",
    text: "Highly recommend! Excellent sound and battery life.",
    likes: 35,
    likedByUser: false,
    replies: [],
  },
  {
    id: 94,
    user: "Sebastian A.",
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    rating: 4.0,
    date: "January 1, 2025",
    text: "Good earbuds, comfortable and decent sound quality.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 95,
    user: "Madison B.",
    avatar: "https://randomuser.me/api/portraits/women/91.jpg",
    rating: 4.8,
    date: "December 30, 2024",
    text: "Battery life is excellent and sound is very clear.",
    likes: 27,
    likedByUser: false,
    replies: [],
  },
  {
    id: 96,
    user: "Oliver W.",
    avatar: "https://randomuser.me/api/portraits/men/92.jpg",
    rating: 4.1,
    date: "December 28, 2024",
    text: "Good value for the money. Comfortable and easy to use.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 97,
    user: "Sophia R.",
    avatar: "https://randomuser.me/api/portraits/women/92.jpg",
    rating: 4.5,
    date: "December 26, 2024",
    text: "Love the earbuds! Great sound and easy connectivity.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 98,
    user: "Benjamin T.",
    avatar: "https://randomuser.me/api/portraits/men/93.jpg",
    rating: 3.7,
    date: "December 24, 2024",
    text: "Sound quality is okay but expected better noise cancellation.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 99,
    user: "Chloe W.",
    avatar: "https://randomuser.me/api/portraits/women/93.jpg",
    rating: 5,
    date: "December 22, 2024",
    text: "Absolutely love these earbuds! Perfect for daily use.",
    likes: 33,
    likedByUser: false,
    replies: [],
  },
  {
    id: 100,
    user: "Jacob K.",
    avatar: "https://randomuser.me/api/portraits/men/94.jpg",
    rating: 4.4,
    date: "December 20, 2024",
    text: "Good sound, comfortable fit, and easy pairing.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 101,
    user: "Zara K.",
    avatar: "https://randomuser.me/api/portraits/women/94.jpg",
    rating: 4.6,
    date: "December 18, 2024",
    text: "Really like these earbuds. Great sound and comfortable to wear for hours.",
    likes: 24,
    likedByUser: false,
    replies: [],
  },
  {
    id: 102,
    user: "Landon M.",
    avatar: "https://randomuser.me/api/portraits/men/95.jpg",
    rating: 3.9,
    date: "December 16, 2024",
    text: "Decent earbuds but sometimes the connection drops randomly.",
    likes: 9,
    likedByUser: false,
    replies: [
      {
        id: 121,
        user: "Nina G.",
        avatar: "https://randomuser.me/api/portraits/women/95.jpg",
        date: "December 17, 2024",
        text: "Try updating the firmware; it fixed connection issues for me.",
        likes: 5,
        likedByUser: false,
      },
    ],
  },
  {
    id: 103,
    user: "Caleb S.",
    avatar: "https://randomuser.me/api/portraits/men/96.jpg",
    rating: 4.8,
    date: "December 14, 2024",
    text: "Excellent earbuds! Sound quality is amazing and battery life is solid.",
    likes: 30,
    likedByUser: false,
    replies: [],
  },
  {
    id: 104,
    user: "Layla D.",
    avatar: "https://randomuser.me/api/portraits/women/96.jpg",
    rating: 4.2,
    date: "December 12, 2024",
    text: "Good earbuds but the charging case feels a bit bulky.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 105,
    user: "Wyatt P.",
    avatar: "https://randomuser.me/api/portraits/men/97.jpg",
    rating: 4.4,
    date: "December 10, 2024",
    text: "Very comfortable fit and solid sound quality overall.",
    likes: 16,
    likedByUser: false,
    replies: [
      {
        id: 122,
        user: "Maya H.",
        avatar: "https://randomuser.me/api/portraits/women/97.jpg",
        date: "December 11, 2024",
        text: "I agree! They stay in place even during intense workouts.",
        likes: 6,
        likedByUser: false,
      },
    ],
  },
  {
    id: 106,
    user: "Julian F.",
    avatar: "https://randomuser.me/api/portraits/men/98.jpg",
    rating: 3.6,
    date: "December 8, 2024",
    text: "Sound quality is okay but I expected better noise cancellation.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 107,
    user: "Zoe N.",
    avatar: "https://randomuser.me/api/portraits/women/98.jpg",
    rating: 5,
    date: "December 6, 2024",
    text: "Best earbuds I've used! Crisp audio and very comfortable.",
    likes: 33,
    likedByUser: false,
    replies: [],
  },
  {
    id: 108,
    user: "Nicholas W.",
    avatar: "https://randomuser.me/api/portraits/men/99.jpg",
    rating: 4.0,
    date: "December 4, 2024",
    text: "Good earbuds with easy pairing and long battery life.",
    likes: 13,
    likedByUser: false,
    replies: [],
  },
  {
    id: 109,
    user: "Hannah Y.",
    avatar: "https://randomuser.me/api/portraits/women/99.jpg",
    rating: 4.7,
    date: "December 2, 2024",
    text: "Excellent noise cancellation and great bass performance.",
    likes: 28,
    likedByUser: false,
    replies: [
      {
        id: 123,
        user: "Ethan G.",
        avatar: "https://randomuser.me/api/portraits/men/100.jpg",
        date: "December 3, 2024",
        text: "Agreed! They block out almost all background noise.",
        likes: 8,
        likedByUser: false,
      },
    ],
  },
  {
    id: 110,
    user: "Avery K.",
    avatar: "https://randomuser.me/api/portraits/women/100.jpg",
    rating: 4.3,
    date: "November 30, 2024",
    text: "Good earbuds but touch controls could be more responsive.",
    likes: 10,
    likedByUser: false,
    replies: [],
  },
  {
    id: 111,
    user: "Ryan C.",
    avatar: "https://randomuser.me/api/portraits/men/101.jpg",
    rating: 3.7,
    date: "November 28, 2024",
    text: "Battery life is decent but I wish charging was faster.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 112,
    user: "Ella V.",
    avatar: "https://randomuser.me/api/portraits/women/101.jpg",
    rating: 5,
    date: "November 26, 2024",
    text: "Absolutely love these earbuds! Perfect for workouts and calls.",
    likes: 35,
    likedByUser: false,
    replies: [],
  },
  {
    id: 113,
    user: "Connor B.",
    avatar: "https://randomuser.me/api/portraits/men/102.jpg",
    rating: 4.5,
    date: "November 24, 2024",
    text: "Great sound quality and very easy to use with my phone.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 114,
    user: "Samantha J.",
    avatar: "https://randomuser.me/api/portraits/women/102.jpg",
    rating: 4.8,
    date: "November 22, 2024",
    text: "The fit is perfect and the sound is crystal clear.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 115,
    user: "Dylan M.",
    avatar: "https://randomuser.me/api/portraits/men/103.jpg",
    rating: 4.1,
    date: "November 20, 2024",
    text: "Good earbuds with reliable Bluetooth connection.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 116,
    user: "Natalie S.",
    avatar: "https://randomuser.me/api/portraits/women/103.jpg",
    rating: 4.4,
    date: "November 18, 2024",
    text: "Battery life is impressive and sound quality is excellent.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 117,
    user: "Isaac F.",
    avatar: "https://randomuser.me/api/portraits/men/104.jpg",
    rating: 3.6,
    date: "November 16, 2024",
    text: "The earbuds are good but sometimes one earbud loses connection.",
    likes: 7,
    likedByUser: false,
    replies: [
      {
        id: 124,
        user: "Alyssa D.",
        avatar: "https://randomuser.me/api/portraits/women/104.jpg",
        date: "November 17, 2024",
        text: "Try resetting them, it helped me with similar issues.",
        likes: 4,
        likedByUser: false,
      },
    ],
  },
  {
    id: 118,
    user: "Violet L.",
    avatar: "https://randomuser.me/api/portraits/women/105.jpg",
    rating: 5,
    date: "November 14, 2024",
    text: "Best earbuds I've had! Great noise cancellation and fit.",
    likes: 31,
    likedByUser: false,
    replies: [],
  },
  {
    id: 119,
    user: "Nathan G.",
    avatar: "https://randomuser.me/api/portraits/men/105.jpg",
    rating: 4.2,
    date: "November 12, 2024",
    text: "Very good earbuds with clear audio and easy controls.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 120,
    user: "Audrey K.",
    avatar: "https://randomuser.me/api/portraits/women/106.jpg",
    rating: 4.6,
    date: "November 10, 2024",
    text: "Comfortable fit and long battery life. Worth the price.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 121,
    user: "Owen R.",
    avatar: "https://randomuser.me/api/portraits/men/106.jpg",
    rating: 3.9,
    date: "November 8, 2024",
    text: "Good sound but the touch controls can be unresponsive sometimes.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 122,
    user: "Leah M.",
    avatar: "https://randomuser.me/api/portraits/women/107.jpg",
    rating: 5,
    date: "November 6, 2024",
    text: "Love these earbuds! The sound is perfect for my daily commute.",
    likes: 34,
    likedByUser: false,
    replies: [],
  },
  {
    id: 123,
    user: "Calvin S.",
    avatar: "https://randomuser.me/api/portraits/men/107.jpg",
    rating: 4.3,
    date: "November 4, 2024",
    text: "Great earbuds, very comfortable and good sound quality.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 124,
    user: "Maya T.",
    avatar: "https://randomuser.me/api/portraits/women/108.jpg",
    rating: 4.7,
    date: "November 2, 2024",
    text: "Excellent battery life and very easy to pair with devices.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 125,
    user: "Eli B.",
    avatar: "https://randomuser.me/api/portraits/men/108.jpg",
    rating: 3.8,
    date: "October 31, 2024",
    text: "Sound quality is good but case is a bit bulky for pockets.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 126,
    user: "Jasmine F.",
    avatar: "https://randomuser.me/api/portraits/women/109.jpg",
    rating: 5,
    date: "October 29, 2024",
    text: "These earbuds exceeded my expectations! Great bass and clarity.",
    likes: 36,
    likedByUser: false,
    replies: [],
  },
  {
    id: 127,
    user: "Luke H.",
    avatar: "https://randomuser.me/api/portraits/men/109.jpg",
    rating: 4.1,
    date: "October 27, 2024",
    text: "Very good earbuds but I wish the touch controls were more accurate.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 128,
    user: "Ava W.",
    avatar: "https://randomuser.me/api/portraits/women/110.jpg",
    rating: 4.5,
    date: "October 25, 2024",
    text: "Comfortable fit and great sound. Battery lasts all day.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 129,
    user: "Ethan K.",
    avatar: "https://randomuser.me/api/portraits/men/110.jpg",
    rating: 3.7,
    date: "October 23, 2024",
    text: "Decent earbuds but connectivity could be better.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 130,
    user: "Ella Q.",
    avatar: "https://randomuser.me/api/portraits/women/111.jpg",
    rating: 5,
    date: "October 21, 2024",
    text: "Best earbuds I've used in a long time! Highly recommend.",
    likes: 38,
    likedByUser: false,
    replies: [],
  },
  {
    id: 131,
    user: "Madison Y.",
    avatar: "https://randomuser.me/api/portraits/women/112.jpg",
    rating: 4.4,
    date: "October 19, 2024",
    text: "Really good earbuds for the price. Sound is clear and bass is decent.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 132,
    user: "James O.",
    avatar: "https://randomuser.me/api/portraits/men/111.jpg",
    rating: 4.0,
    date: "October 17, 2024",
    text: "Comfortable fit but sometimes connection drops if too far from phone.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 133,
    user: "Ella S.",
    avatar: "https://randomuser.me/api/portraits/women/113.jpg",
    rating: 5,
    date: "October 15, 2024",
    text: "Love these earbuds! Great noise cancellation and long battery life.",
    likes: 30,
    likedByUser: false,
    replies: [
      {
        id: 125,
        user: "David K.",
        avatar: "https://randomuser.me/api/portraits/men/112.jpg",
        date: "October 16, 2024",
        text: "Totally agree, battery lasts me all day with heavy use.",
        likes: 7,
        likedByUser: false,
      },
    ],
  },
  {
    id: 134,
    user: "Oliver J.",
    avatar: "https://randomuser.me/api/portraits/men/113.jpg",
    rating: 4.3,
    date: "October 13, 2024",
    text: "Good sound and decent comfort but charging case is a bit bulky.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 135,
    user: "Grace W.",
    avatar: "https://randomuser.me/api/portraits/women/114.jpg",
    rating: 4.7,
    date: "October 11, 2024",
    text: "Very comfortable earbuds with excellent sound quality.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 136,
    user: "Lucas P.",
    avatar: "https://randomuser.me/api/portraits/men/114.jpg",
    rating: 3.9,
    date: "October 9, 2024",
    text: "Bluetooth connectivity sometimes drops, but otherwise good sound.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 137,
    user: "Sophia A.",
    avatar: "https://randomuser.me/api/portraits/women/115.jpg",
    rating: 5,
    date: "October 7, 2024",
    text: "Amazing earbuds! Great noise cancellation and comfy fit for long use.",
    likes: 33,
    likedByUser: false,
    replies: [],
  },
  {
    id: 138,
    user: "Mason C.",
    avatar: "https://randomuser.me/api/portraits/men/115.jpg",
    rating: 4.2,
    date: "October 5, 2024",
    text: "Good quality earbuds with solid battery life.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 139,
    user: "Isabella M.",
    avatar: "https://randomuser.me/api/portraits/women/116.jpg",
    rating: 4.5,
    date: "October 3, 2024",
    text: "Really like the sound quality and ease of use.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 140,
    user: "Ethan Q.",
    avatar: "https://randomuser.me/api/portraits/men/116.jpg",
    rating: 3.8,
    date: "October 1, 2024",
    text: "Decent earbuds but touch controls can be frustrating at times.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 141,
    user: "Ava H.",
    avatar: "https://randomuser.me/api/portraits/women/117.jpg",
    rating: 5,
    date: "September 29, 2024",
    text: "Best earbuds I've used so far. Crystal clear sound and great fit.",
    likes: 36,
    likedByUser: false,
    replies: [],
  },
  {
    id: 142,
    user: "Benjamin T.",
    avatar: "https://randomuser.me/api/portraits/men/117.jpg",
    rating: 4.1,
    date: "September 27, 2024",
    text: "Comfortable fit and solid connection. Worth the price.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 143,
    user: "Lily C.",
    avatar: "https://randomuser.me/api/portraits/women/118.jpg",
    rating: 4.4,
    date: "September 25, 2024",
    text: "Very good earbuds with good bass and clear highs.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 144,
    user: "Noah W.",
    avatar: "https://randomuser.me/api/portraits/men/118.jpg",
    rating: 3.7,
    date: "September 23, 2024",
    text: "Battery life is average but sound quality is good.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 145,
    user: "Ella N.",
    avatar: "https://randomuser.me/api/portraits/women/119.jpg",
    rating: 5,
    date: "September 21, 2024",
    text: "Highly recommend! Great for calls and music.",
    likes: 35,
    likedByUser: false,
    replies: [],
  },
  {
    id: 146,
    user: "Oliver F.",
    avatar: "https://randomuser.me/api/portraits/men/119.jpg",
    rating: 4.3,
    date: "September 19, 2024",
    text: "Good sound quality and very easy to pair.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 147,
    user: "Mia G.",
    avatar: "https://randomuser.me/api/portraits/women/120.jpg",
    rating: 4.6,
    date: "September 17, 2024",
    text: "Battery lasts long and sound is clear. Very happy with purchase.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 148,
    user: "Jack H.",
    avatar: "https://randomuser.me/api/portraits/men/120.jpg",
    rating: 3.9,
    date: "September 15, 2024",
    text: "Good earbuds but case size could be smaller.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 149,
    user: "Chloe J.",
    avatar: "https://randomuser.me/api/portraits/women/121.jpg",
    rating: 5,
    date: "September 13, 2024",
    text: "Love these earbuds! They stay in place and sound amazing.",
    likes: 37,
    likedByUser: false,
    replies: [],
  },
  {
    id: 150,
    user: "Logan K.",
    avatar: "https://randomuser.me/api/portraits/men/121.jpg",
    rating: 4.2,
    date: "September 11, 2024",
    text: "Great earbuds with strong Bluetooth connection.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 151,
    user: "Amelia L.",
    avatar: "https://randomuser.me/api/portraits/women/122.jpg",
    rating: 4.5,
    date: "September 9, 2024",
    text: "Comfortable and great sound for the price.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 152,
    user: "Lucas M.",
    avatar: "https://randomuser.me/api/portraits/men/122.jpg",
    rating: 3.8,
    date: "September 7, 2024",
    text: "Decent earbuds but expected better noise cancellation.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 153,
    user: "Sophia N.",
    avatar: "https://randomuser.me/api/portraits/women/123.jpg",
    rating: 5,
    date: "September 5, 2024",
    text: "Amazing earbuds with long battery life and clear sound.",
    likes: 38,
    likedByUser: false,
    replies: [],
  },
  {
    id: 154,
    user: "Mason O.",
    avatar: "https://randomuser.me/api/portraits/men/123.jpg",
    rating: 4.1,
    date: "September 3, 2024",
    text: "Good fit and solid sound. Works well during workouts.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 155,
    user: "Isabella P.",
    avatar: "https://randomuser.me/api/portraits/women/124.jpg",
    rating: 4.4,
    date: "September 1, 2024",
    text: "Very happy with these earbuds! Battery lasts long and sound is great.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 156,
    user: "Ethan Q.",
    avatar: "https://randomuser.me/api/portraits/men/124.jpg",
    rating: 3.7,
    date: "August 30, 2024",
    text: "Good earbuds but sometimes touch controls are unresponsive.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 157,
    user: "Ava R.",
    avatar: "https://randomuser.me/api/portraits/women/125.jpg",
    rating: 5,
    date: "August 28, 2024",
    text: "Love these earbuds! Great for calls and music with excellent clarity.",
    likes: 39,
    likedByUser: false,
    replies: [],
  },
  {
    id: 158,
    user: "Benjamin S.",
    avatar: "https://randomuser.me/api/portraits/men/125.jpg",
    rating: 4.2,
    date: "August 26, 2024",
    text: "Comfortable earbuds with strong Bluetooth connection.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 159,
    user: "Lily T.",
    avatar: "https://randomuser.me/api/portraits/women/126.jpg",
    rating: 4.6,
    date: "August 24, 2024",
    text: "Battery life is impressive and sound quality is clear.",
    likes: 23,
    likedByUser: false,
    replies: [],
  },
  {
    id: 160,
    user: "Noah U.",
    avatar: "https://randomuser.me/api/portraits/men/126.jpg",
    rating: 3.9,
    date: "August 22, 2024",
    text: "Good earbuds but expected better noise cancellation.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 200,
    user: "Harper V.",
    avatar: "https://randomuser.me/api/portraits/women/127.jpg",
    rating: 4.7,
    date: "August 20, 2024",
    text: "The sound quality blew me away. Very comfortable for long use too.",
    likes: 26,
    likedByUser: false,
    replies: [],
  },
  {
    id: 201,
    user: "Jackson W.",
    avatar: "https://randomuser.me/api/portraits/men/127.jpg",
    rating: 3.8,
    date: "August 18, 2024",
    text: "Good earbuds but Bluetooth connection is a bit unstable sometimes.",
    likes: 10,
    likedByUser: false,
    replies: [],
  },
  {
    id: 202,
    user: "Ella X.",
    avatar: "https://randomuser.me/api/portraits/women/128.jpg",
    rating: 5,
    date: "August 16, 2024",
    text: "Absolutely love these earbuds! Great noise cancellation and battery life.",
    likes: 37,
    likedByUser: false,
    replies: [
      {
        id: 300,
        user: "Lucas Y.",
        avatar: "https://randomuser.me/api/portraits/men/128.jpg",
        date: "August 17, 2024",
        text: "Agreed! They last me all day without any issues.",
        likes: 8,
        likedByUser: false,
      },
    ],
  },
  {
    id: 203,
    user: "Mia Z.",
    avatar: "https://randomuser.me/api/portraits/women/129.jpg",
    rating: 4.1,
    date: "August 14, 2024",
    text: "Good sound but wish the case was smaller and lighter.",
    likes: 12,
    likedByUser: false,
    replies: [],
  },
  {
    id: 204,
    user: "Liam A.",
    avatar: "https://randomuser.me/api/portraits/men/129.jpg",
    rating: 4.5,
    date: "August 12, 2024",
    text: "Very comfortable earbuds and the bass is punchy and clear.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 205,
    user: "Zoe B.",
    avatar: "https://randomuser.me/api/portraits/women/130.jpg",
    rating: 3.7,
    date: "August 10, 2024",
    text: "Bluetooth connection sometimes drops if I move too far from phone.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 206,
    user: "Noah C.",
    avatar: "https://randomuser.me/api/portraits/men/130.jpg",
    rating: 5,
    date: "August 8, 2024",
    text: "Best earbuds I’ve used so far! Great sound and very comfortable.",
    likes: 34,
    likedByUser: false,
    replies: [],
  },
  {
    id: 207,
    user: "Avery D.",
    avatar: "https://randomuser.me/api/portraits/women/131.jpg",
    rating: 4.3,
    date: "August 6, 2024",
    text: "Good quality earbuds with long battery life.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 208,
    user: "Mason E.",
    avatar: "https://randomuser.me/api/portraits/men/131.jpg",
    rating: 4.0,
    date: "August 4, 2024",
    text: "Sound quality is clear but touch controls can be a bit tricky.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 209,
    user: "Ella F.",
    avatar: "https://randomuser.me/api/portraits/women/132.jpg",
    rating: 5,
    date: "August 2, 2024",
    text: "Perfect earbuds! Great for working out and daily use.",
    likes: 38,
    likedByUser: false,
    replies: [],
  },
  {
    id: 210,
    user: "Logan G.",
    avatar: "https://randomuser.me/api/portraits/men/132.jpg",
    rating: 4.2,
    date: "July 31, 2024",
    text: "Comfortable fit and solid sound quality overall.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 211,
    user: "Sophia H.",
    avatar: "https://randomuser.me/api/portraits/women/133.jpg",
    rating: 4.6,
    date: "July 29, 2024",
    text: "Battery lasts all day and sound is very crisp and clear.",
    likes: 23,
    likedByUser: false,
    replies: [],
  },
  {
    id: 212,
    user: "James I.",
    avatar: "https://randomuser.me/api/portraits/men/133.jpg",
    rating: 3.9,
    date: "July 27, 2024",
    text: "Good earbuds but expected a bit better noise isolation.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 213,
    user: "Isabella J.",
    avatar: "https://randomuser.me/api/portraits/women/134.jpg",
    rating: 5,
    date: "July 25, 2024",
    text: "Love these earbuds! Great sound and very comfortable for long wear.",
    likes: 40,
    likedByUser: false,
    replies: [],
  },
  {
    id: 214,
    user: "Oliver K.",
    avatar: "https://randomuser.me/api/portraits/men/134.jpg",
    rating: 4.4,
    date: "July 23, 2024",
    text: "Very good earbuds with easy pairing and great battery life.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 215,
    user: "Mia L.",
    avatar: "https://randomuser.me/api/portraits/women/135.jpg",
    rating: 4.8,
    date: "July 21, 2024",
    text: "Excellent sound quality and super comfortable fit.",
    likes: 27,
    likedByUser: false,
    replies: [],
  },
  {
    id: 216,
    user: "Liam M.",
    avatar: "https://randomuser.me/api/portraits/men/135.jpg",
    rating: 3.6,
    date: "July 19, 2024",
    text: "Decent earbuds but the touch controls can be unresponsive at times.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 217,
    user: "Emily N.",
    avatar: "https://randomuser.me/api/portraits/women/136.jpg",
    rating: 5,
    date: "July 17, 2024",
    text: "Best earbuds I've owned! Great noise cancellation and battery life.",
    likes: 42,
    likedByUser: false,
    replies: [],
  },
  {
    id: 218,
    user: "Noah O.",
    avatar: "https://randomuser.me/api/portraits/men/136.jpg",
    rating: 4.1,
    date: "July 15, 2024",
    text: "Comfortable earbuds with solid sound and reliable connection.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 219,
    user: "Olivia P.",
    avatar: "https://randomuser.me/api/portraits/women/137.jpg",
    rating: 4.5,
    date: "July 13, 2024",
    text: "Very happy with these earbuds! Great battery life and sound.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 220,
    user: "Ethan Q.",
    avatar: "https://randomuser.me/api/portraits/men/137.jpg",
    rating: 3.8,
    date: "July 11, 2024",
    text: "Good earbuds but the charging case is a bit bulky for pockets.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 221,
    user: "Amelia R.",
    avatar: "https://randomuser.me/api/portraits/women/138.jpg",
    rating: 5,
    date: "July 9, 2024",
    text: "Love these earbuds! Perfect for music and calls.",
    likes: 44,
    likedByUser: false,
    replies: [],
  },
  {
    id: 222,
    user: "Jacob S.",
    avatar: "https://randomuser.me/api/portraits/men/138.jpg",
    rating: 4.3,
    date: "July 7, 2024",
    text: "Great earbuds with easy setup and good sound quality.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 223,
    user: "Mila T.",
    avatar: "https://randomuser.me/api/portraits/women/139.jpg",
    rating: 4.7,
    date: "July 5, 2024",
    text: "Excellent battery life and very comfortable to wear.",
    likes: 23,
    likedByUser: false,
    replies: [],
  },
  {
    id: 224,
    user: "William U.",
    avatar: "https://randomuser.me/api/portraits/men/139.jpg",
    rating: 3.9,
    date: "July 3, 2024",
    text: "Good sound quality but sometimes one earbud loses connection.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 225,
    user: "Ella V.",
    avatar: "https://randomuser.me/api/portraits/women/140.jpg",
    rating: 5,
    date: "July 1, 2024",
    text: "Highly recommend! Perfect earbuds for everyday use.",
    likes: 39,
    likedByUser: false,
    replies: [],
  },
  {
    id: 226,
    user: "Michael W.",
    avatar: "https://randomuser.me/api/portraits/men/140.jpg",
    rating: 4.4,
    date: "June 29, 2024",
    text: "Very good earbuds with strong Bluetooth connection.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 227,
    user: "Zoe X.",
    avatar: "https://randomuser.me/api/portraits/women/141.jpg",
    rating: 4.8,
    date: "June 27, 2024",
    text: "Great sound and very comfortable fit.",
    likes: 27,
    likedByUser: false,
    replies: [],
  },
  {
    id: 228,
    user: "Daniel Y.",
    avatar: "https://randomuser.me/api/portraits/men/141.jpg",
    rating: 3.7,
    date: "June 25, 2024",
    text: "Decent earbuds but expected better battery life.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 229,
    user: "Lily Z.",
    avatar: "https://randomuser.me/api/portraits/women/142.jpg",
    rating: 5,
    date: "June 23, 2024",
    text: "Amazing earbuds with crisp sound and long-lasting battery.",
    likes: 40,
    likedByUser: false,
    replies: [],
  },
  {
    id: 230,
    user: "James A.",
    avatar: "https://randomuser.me/api/portraits/men/142.jpg",
    rating: 4.1,
    date: "June 21, 2024",
    text: "Comfortable earbuds with good bass and clear highs.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 231,
    user: "Madison B.",
    avatar: "https://randomuser.me/api/portraits/women/143.jpg",
    rating: 4.5,
    date: "June 19, 2024",
    text: "Very happy with these earbuds! Easy to use and great sound.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 232,
    user: "Benjamin C.",
    avatar: "https://randomuser.me/api/portraits/men/143.jpg",
    rating: 3.8,
    date: "June 17, 2024",
    text: "Good earbuds but sometimes the touch controls don’t respond.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 233,
    user: "Ella D.",
    avatar: "https://randomuser.me/api/portraits/women/144.jpg",
    rating: 5,
    date: "June 15, 2024",
    text: "Love these earbuds! Perfect for workouts and calls.",
    likes: 41,
    likedByUser: false,
    replies: [],
  },
  {
    id: 234,
    user: "Oliver E.",
    avatar: "https://randomuser.me/api/portraits/men/144.jpg",
    rating: 4.2,
    date: "June 13, 2024",
    text: "Good sound and reliable connection.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 235,
    user: "Sophia F.",
    avatar: "https://randomuser.me/api/portraits/women/145.jpg",
    rating: 4.6,
    date: "June 11, 2024",
    text: "Battery lasts long and the fit is very comfortable.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 236,
    user: "Logan G.",
    avatar: "https://randomuser.me/api/portraits/men/145.jpg",
    rating: 3.9,
    date: "June 9, 2024",
    text: "Good earbuds but expected better noise cancellation.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 237,
    user: "Avery H.",
    avatar: "https://randomuser.me/api/portraits/women/146.jpg",
    rating: 5,
    date: "June 7, 2024",
    text: "Best earbuds I’ve owned! Great sound and very comfortable.",
    likes: 45,
    likedByUser: false,
    replies: [],
  },
  {
    id: 238,
    user: "Michael I.",
    avatar: "https://randomuser.me/api/portraits/men/146.jpg",
    rating: 4.1,
    date: "June 5, 2024",
    text: "Comfortable fit and strong Bluetooth connection.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 239,
    user: "Chloe J.",
    avatar: "https://randomuser.me/api/portraits/women/147.jpg",
    rating: 4.4,
    date: "June 3, 2024",
    text: "Very good earbuds with clear audio and good bass.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 240,
    user: "William K.",
    avatar: "https://randomuser.me/api/portraits/men/147.jpg",
    rating: 3.7,
    date: "June 1, 2024",
    text: "Battery life is average but sound quality is decent.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 300,
    user: "Zara L.",
    avatar: "https://randomuser.me/api/portraits/women/148.jpg",
    rating: 4.9,
    date: "May 30, 2024",
    text: "Incredible sound clarity and very comfortable fit. These earbuds exceeded my expectations!",
    likes: 45,
    likedByUser: false,
    replies: [],
  },
  {
    id: 301,
    user: "Caleb M.",
    avatar: "https://randomuser.me/api/portraits/men/148.jpg",
    rating: 3.6,
    date: "May 28, 2024",
    text: "Decent earbuds but the Bluetooth occasionally disconnects during runs.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 302,
    user: "Nina P.",
    avatar: "https://randomuser.me/api/portraits/women/149.jpg",
    rating: 5,
    date: "May 26, 2024",
    text: "Love these! Battery lasts all day and noise cancellation works great.",
    likes: 42,
    likedByUser: false,
    replies: [
      {
        id: 400,
        user: "Jack R.",
        avatar: "https://randomuser.me/api/portraits/men/149.jpg",
        date: "May 27, 2024",
        text: "Same here, great earbuds for the price!",
        likes: 10,
        likedByUser: false,
      },
    ],
  },
  {
    id: 303,
    user: "Leah S.",
    avatar: "https://randomuser.me/api/portraits/women/150.jpg",
    rating: 4.2,
    date: "May 24, 2024",
    text: "Good sound quality but the touch controls can be a bit sensitive.",
    likes: 14,
    likedByUser: false,
    replies: [],
  },
  {
    id: 304,
    user: "Ethan T.",
    avatar: "https://randomuser.me/api/portraits/men/150.jpg",
    rating: 4.8,
    date: "May 22, 2024",
    text: "Very comfortable earbuds and the sound is rich and clear.",
    likes: 29,
    likedByUser: false,
    replies: [],
  },
  {
    id: 305,
    user: "Sophia U.",
    avatar: "https://randomuser.me/api/portraits/women/151.jpg",
    rating: 3.9,
    date: "May 20, 2024",
    text: "Bluetooth occasionally drops, but overall good value for money.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 306,
    user: "Liam V.",
    avatar: "https://randomuser.me/api/portraits/men/151.jpg",
    rating: 5,
    date: "May 18, 2024",
    text: "Best earbuds I've ever had! Great noise cancellation and long battery life.",
    likes: 40,
    likedByUser: false,
    replies: [],
  },
  {
    id: 307,
    user: "Emma W.",
    avatar: "https://randomuser.me/api/portraits/women/152.jpg",
    rating: 4.3,
    date: "May 16, 2024",
    text: "Good build quality and sound is balanced.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 308,
    user: "Noah X.",
    avatar: "https://randomuser.me/api/portraits/men/152.jpg",
    rating: 4.0,
    date: "May 14, 2024",
    text: "Works well but sometimes the fit isn't perfect during workouts.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 309,
    user: "Isabella Y.",
    avatar: "https://randomuser.me/api/portraits/women/153.jpg",
    rating: 5,
    date: "May 12, 2024",
    text: "I’m obsessed! Battery lasts all day and the earbuds are very comfortable.",
    likes: 48,
    likedByUser: false,
    replies: [],
  },
  {
    id: 310,
    user: "Mason Z.",
    avatar: "https://randomuser.me/api/portraits/men/153.jpg",
    rating: 4.2,
    date: "May 10, 2024",
    text: "Good sound and easy pairing. A little pricey but worth it.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 311,
    user: "Ava A.",
    avatar: "https://randomuser.me/api/portraits/women/154.jpg",
    rating: 4.6,
    date: "May 8, 2024",
    text: "Great earbuds with a snug fit. Perfect for daily use.",
    likes: 25,
    likedByUser: false,
    replies: [],
  },
  {
    id: 312,
    user: "James B.",
    avatar: "https://randomuser.me/api/portraits/men/154.jpg",
    rating: 3.7,
    date: "May 6, 2024",
    text: "Average battery life and controls could be better.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 313,
    user: "Mia C.",
    avatar: "https://randomuser.me/api/portraits/women/155.jpg",
    rating: 5,
    date: "May 4, 2024",
    text: "Highly recommend! These earbuds handle calls beautifully and the sound is crisp.",
    likes: 44,
    likedByUser: false,
    replies: [],
  },
  {
    id: 314,
    user: "Logan D.",
    avatar: "https://randomuser.me/api/portraits/men/155.jpg",
    rating: 4.1,
    date: "May 2, 2024",
    text: "Comfortable and reliable with good sound quality.",
    likes: 16,
    likedByUser: false,
    replies: [],
  },
  {
    id: 315,
    user: "Emily E.",
    avatar: "https://randomuser.me/api/portraits/women/156.jpg",
    rating: 4.5,
    date: "April 30, 2024",
    text: "Great battery life and sound clarity. Very happy with my purchase.",
    likes: 22,
    likedByUser: false,
    replies: [],
  },
  {
    id: 316,
    user: "Benjamin F.",
    avatar: "https://randomuser.me/api/portraits/men/156.jpg",
    rating: 3.8,
    date: "April 28, 2024",
    text: "Decent earbuds but could improve on noise isolation.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 317,
    user: "Ella G.",
    avatar: "https://randomuser.me/api/portraits/women/157.jpg",
    rating: 5,
    date: "April 26, 2024",
    text: "Amazing sound and fit. Battery lasts all day with heavy use.",
    likes: 50,
    likedByUser: false,
    replies: [],
  },
  {
    id: 318,
    user: "Oliver H.",
    avatar: "https://randomuser.me/api/portraits/men/157.jpg",
    rating: 4.3,
    date: "April 24, 2024",
    text: "Good earbuds with solid build quality and nice sound.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 319,
    user: "Sophia I.",
    avatar: "https://randomuser.me/api/portraits/women/158.jpg",
    rating: 4.7,
    date: "April 22, 2024",
    text: "Comfortable for long wear and sound is top notch.",
    likes: 26,
    likedByUser: false,
    replies: [],
  },
  {
    id: 320,
    user: "Jack J.",
    avatar: "https://randomuser.me/api/portraits/men/158.jpg",
    rating: 3.9,
    date: "April 20, 2024",
    text: "Good value but controls could be more responsive.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 321,
    user: "Lily K.",
    avatar: "https://randomuser.me/api/portraits/women/159.jpg",
    rating: 5,
    date: "April 18, 2024",
    text: "Love these earbuds! Perfect sound, perfect fit.",
    likes: 47,
    likedByUser: false,
    replies: [],
  },
  {
    id: 322,
    user: "William L.",
    avatar: "https://randomuser.me/api/portraits/men/159.jpg",
    rating: 4.2,
    date: "April 16, 2024",
    text: "Very good sound and battery life.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
  {
    id: 323,
    user: "Zoe M.",
    avatar: "https://randomuser.me/api/portraits/women/160.jpg",
    rating: 4.6,
    date: "April 14, 2024",
    text: "Comfortable and great sound for the price.",
    likes: 25,
    likedByUser: false,
    replies: [],
  },
  {
    id: 324,
    user: "Daniel N.",
    avatar: "https://randomuser.me/api/portraits/men/160.jpg",
    rating: 3.7,
    date: "April 12, 2024",
    text: "Battery life could be better but sound is decent.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 325,
    user: "Madison O.",
    avatar: "https://randomuser.me/api/portraits/women/161.jpg",
    rating: 5,
    date: "April 10, 2024",
    text: "Excellent earbuds, I use them daily without any issues.",
    likes: 48,
    likedByUser: false,
    replies: [],
  },
  {
    id: 326,
    user: "Michael P.",
    avatar: "https://randomuser.me/api/portraits/men/161.jpg",
    rating: 4.1,
    date: "April 8, 2024",
    text: "Good earbuds with clear audio and reliable connection.",
    likes: 17,
    likedByUser: false,
    replies: [],
  },
  {
    id: 327,
    user: "Chloe Q.",
    avatar: "https://randomuser.me/api/portraits/women/162.jpg",
    rating: 4.4,
    date: "April 6, 2024",
    text: "Very comfortable and sound is impressive for the price.",
    likes: 23,
    likedByUser: false,
    replies: [],
  },
  {
    id: 328,
    user: "James R.",
    avatar: "https://randomuser.me/api/portraits/men/162.jpg",
    rating: 3.8,
    date: "April 4, 2024",
    text: "Decent earbuds but sometimes touch controls are a bit laggy.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 329,
    user: "Emily S.",
    avatar: "https://randomuser.me/api/portraits/women/163.jpg",
    rating: 5,
    date: "April 2, 2024",
    text: "Highly recommend! Great sound and very comfortable to wear.",
    likes: 50,
    likedByUser: false,
    replies: [],
  },
  {
    id: 330,
    user: "Oliver T.",
    avatar: "https://randomuser.me/api/portraits/men/163.jpg",
    rating: 4.3,
    date: "March 31, 2024",
    text: "Good fit and sound quality, works well even during exercise.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 400,
    user: "Ella U.",
    avatar: "https://randomuser.me/api/portraits/women/164.jpg",
    rating: 4.7,
    date: "March 29, 2024",
    text: "Outstanding earbuds with excellent sound clarity and very comfy fit.",
    likes: 36,
    likedByUser: false,
    replies: [],
  },
  {
    id: 401,
    user: "Jackson V.",
    avatar: "https://randomuser.me/api/portraits/men/164.jpg",
    rating: 3.9,
    date: "March 27, 2024",
    text: "Good earbuds but occasionally lose connection during runs.",
    likes: 11,
    likedByUser: false,
    replies: [],
  },
  {
    id: 402,
    user: "Mia W.",
    avatar: "https://randomuser.me/api/portraits/women/165.jpg",
    rating: 5,
    date: "March 25, 2024",
    text: "Love these! Battery life is amazing and noise cancellation is very effective.",
    likes: 44,
    likedByUser: false,
    replies: [
      {
        id: 500,
        user: "Lucas X.",
        avatar: "https://randomuser.me/api/portraits/men/165.jpg",
        date: "March 26, 2024",
        text: "Totally agree, these are the best earbuds I’ve tried so far!",
        likes: 12,
        likedByUser: false,
      },
    ],
  },
  {
    id: 403,
    user: "Leah Y.",
    avatar: "https://randomuser.me/api/portraits/women/166.jpg",
    rating: 4.3,
    date: "March 23, 2024",
    text: "Very good sound quality, but touch controls need improvement.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 404,
    user: "Ethan Z.",
    avatar: "https://randomuser.me/api/portraits/men/166.jpg",
    rating: 4.9,
    date: "March 21, 2024",
    text: "Comfortable and clear sound. The bass is powerful but not overwhelming.",
    likes: 31,
    likedByUser: false,
    replies: [],
  },
  {
    id: 405,
    user: "Sophia A.",
    avatar: "https://randomuser.me/api/portraits/women/167.jpg",
    rating: 3.8,
    date: "March 19, 2024",
    text: "Good product but sometimes the Bluetooth disconnects randomly.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 406,
    user: "Liam B.",
    avatar: "https://randomuser.me/api/portraits/men/167.jpg",
    rating: 5,
    date: "March 17, 2024",
    text: "Perfect earbuds with excellent battery life and sound quality.",
    likes: 39,
    likedByUser: false,
    replies: [],
  },
  {
    id: 407,
    user: "Emma C.",
    avatar: "https://randomuser.me/api/portraits/women/168.jpg",
    rating: 4.4,
    date: "March 15, 2024",
    text: "Great fit, sound is balanced and clear.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 408,
    user: "Noah D.",
    avatar: "https://randomuser.me/api/portraits/men/168.jpg",
    rating: 4.1,
    date: "March 13, 2024",
    text: "Good earbuds but could be a bit better for workouts.",
    likes: 13,
    likedByUser: false,
    replies: [],
  },
  {
    id: 409,
    user: "Isabella E.",
    avatar: "https://randomuser.me/api/portraits/women/169.jpg",
    rating: 5,
    date: "March 11, 2024",
    text: "I love these! Battery lasts all day and noise cancelling is impressive.",
    likes: 49,
    likedByUser: false,
    replies: [],
  },
  {
    id: 410,
    user: "Mason F.",
    avatar: "https://randomuser.me/api/portraits/men/169.jpg",
    rating: 4.3,
    date: "March 9, 2024",
    text: "Great earbuds with easy pairing. Slightly bulky charging case.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 411,
    user: "Ava G.",
    avatar: "https://randomuser.me/api/portraits/women/170.jpg",
    rating: 4.7,
    date: "March 7, 2024",
    text: "Super comfortable and sound quality is impressive.",
    likes: 26,
    likedByUser: false,
    replies: [],
  },
  {
    id: 412,
    user: "James H.",
    avatar: "https://randomuser.me/api/portraits/men/170.jpg",
    rating: 3.5,
    date: "March 5, 2024",
    text: "Battery life could be improved. Controls are okay.",
    likes: 6,
    likedByUser: false,
    replies: [],
  },
  {
    id: 413,
    user: "Mia I.",
    avatar: "https://randomuser.me/api/portraits/women/171.jpg",
    rating: 5,
    date: "March 3, 2024",
    text: "Best earbuds for calls and music. Highly recommended.",
    likes: 46,
    likedByUser: false,
    replies: [],
  },
  {
    id: 414,
    user: "Logan J.",
    avatar: "https://randomuser.me/api/portraits/men/171.jpg",
    rating: 4.0,
    date: "March 1, 2024",
    text: "Comfortable and reliable with decent sound quality.",
    likes: 15,
    likedByUser: false,
    replies: [],
  },
  {
    id: 415,
    user: "Emily K.",
    avatar: "https://randomuser.me/api/portraits/women/172.jpg",
    rating: 4.5,
    date: "February 27, 2024",
    text: "Great battery life and crystal clear audio.",
    likes: 24,
    likedByUser: false,
    replies: [],
  },
  {
    id: 416,
    user: "Benjamin L.",
    avatar: "https://randomuser.me/api/portraits/men/172.jpg",
    rating: 3.9,
    date: "February 25, 2024",
    text: "Good earbuds but sometimes noise cancellation is not perfect.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 417,
    user: "Ella M.",
    avatar: "https://randomuser.me/api/portraits/women/173.jpg",
    rating: 5,
    date: "February 23, 2024",
    text: "Amazing sound and comfortable fit, battery lasts long.",
    likes: 51,
    likedByUser: false,
    replies: [],
  },
  {
    id: 418,
    user: "Oliver N.",
    avatar: "https://randomuser.me/api/portraits/men/173.jpg",
    rating: 4.2,
    date: "February 21, 2024",
    text: "Good earbuds with solid sound and build quality.",
    likes: 19,
    likedByUser: false,
    replies: [],
  },
  {
    id: 419,
    user: "Sophia O.",
    avatar: "https://randomuser.me/api/portraits/women/174.jpg",
    rating: 4.8,
    date: "February 19, 2024",
    text: "Perfect for long listening sessions, very comfortable.",
    likes: 27,
    likedByUser: false,
    replies: [],
  },
  {
    id: 420,
    user: "Jack P.",
    avatar: "https://randomuser.me/api/portraits/men/174.jpg",
    rating: 3.6,
    date: "February 17, 2024",
    text: "Decent earbuds but touch controls can be unresponsive at times.",
    likes: 8,
    likedByUser: false,
    replies: [],
  },
  {
    id: 421,
    user: "Lily Q.",
    avatar: "https://randomuser.me/api/portraits/women/175.jpg",
    rating: 5,
    date: "February 15, 2024",
    text: "Love these earbuds! Crisp sound and comfortable fit.",
    likes: 48,
    likedByUser: false,
    replies: [],
  },
  {
    id: 422,
    user: "William R.",
    avatar: "https://randomuser.me/api/portraits/men/175.jpg",
    rating: 4.3,
    date: "February 13, 2024",
    text: "Good sound quality and long battery life.",
    likes: 21,
    likedByUser: false,
    replies: [],
  },
  {
    id: 423,
    user: "Zoe S.",
    avatar: "https://randomuser.me/api/portraits/women/176.jpg",
    rating: 4.6,
    date: "February 11, 2024",
    text: "Very comfortable and clear sound for the price.",
    likes: 26,
    likedByUser: false,
    replies: [],
  },
  {
    id: 424,
    user: "Daniel T.",
    avatar: "https://randomuser.me/api/portraits/men/176.jpg",
    rating: 3.7,
    date: "February 9, 2024",
    text: "Battery life could be better but sound is decent overall.",
    likes: 7,
    likedByUser: false,
    replies: [],
  },
  {
    id: 425,
    user: "Madison U.",
    avatar: "https://randomuser.me/api/portraits/women/177.jpg",
    rating: 5,
    date: "February 7, 2024",
    text: "Excellent earbuds, perfect for everyday use.",
    likes: 49,
    likedByUser: false,
    replies: [],
  },
  {
    id: 426,
    user: "Michael V.",
    avatar: "https://randomuser.me/api/portraits/men/177.jpg",
    rating: 4.2,
    date: "February 5, 2024",
    text: "Good sound and reliable connection.",
    likes: 18,
    likedByUser: false,
    replies: [],
  },
  {
    id: 427,
    user: "Chloe W.",
    avatar: "https://randomuser.me/api/portraits/women/178.jpg",
    rating: 4.5,
    date: "February 3, 2024",
    text: "Very comfortable earbuds with impressive sound.",
    likes: 24,
    likedByUser: false,
    replies: [],
  },
  {
    id: 428,
    user: "James X.",
    avatar: "https://randomuser.me/api/portraits/men/178.jpg",
    rating: 3.9,
    date: "February 1, 2024",
    text: "Decent earbuds but the touch controls could be improved.",
    likes: 9,
    likedByUser: false,
    replies: [],
  },
  {
    id: 429,
    user: "Emily Y.",
    avatar: "https://randomuser.me/api/portraits/women/179.jpg",
    rating: 5,
    date: "January 30, 2024",
    text: "Highly recommend! Great sound and fit.",
    likes: 52,
    likedByUser: false,
    replies: [],
  },
  {
    id: 430,
    user: "Oliver Z.",
    avatar: "https://randomuser.me/api/portraits/men/179.jpg",
    rating: 4.1,
    date: "January 28, 2024",
    text: "Good earbuds with clear audio and reliable battery.",
    likes: 20,
    likedByUser: false,
    replies: [],
  },
];

// Star rendering function with half star clipping
const renderStars = (rating) => {
  const stars = [];
  const fullStars = Math.floor(rating);
  const halfStar = rating - fullStars >= 0.5;
  for (let i = 0; i < fullStars; i++) {
    stars.push(
      <AiFillStar
        key={"full-" + i}
        className="text-amber-600 w-5 h-5"
        aria-hidden="true"
      />
    );
  }
  if (halfStar) {
    stars.push(
      <AiFillStar
        key="half"
        className="text-amber-600 w-5 h-5"
        style={{ clipPath: "inset(0 50% 0 0)" }}
        aria-hidden="true"
      />
    );
  }
  const emptyStars = 5 - stars.length;
  for (let i = 0; i < emptyStars; i++) {
    stars.push(
      <AiOutlineStar
        key={"empty-" + i}
        className="text-amber-600 w-5 h-5"
        aria-hidden="true"
      />
    );
  }
  return stars;
};

const ProductReviewsAdvanced = () => {
  const [reviews, setReviews] = useState(initialReviews);
  const [replyingTo, setReplyingTo] = useState(null);
  const [replyText, setReplyText] = useState("");
  const [visibleCount, setVisibleCount] = useState(2);

  const toggleLike = (reviewId, replyId = null) => {
    setReviews((prev) =>
      prev.map((review) => {
        if (review.id === reviewId) {
          if (replyId === null) {
            const liked = !review.likedByUser;
            return {
              ...review,
              likedByUser: liked,
              likes: liked ? review.likes + 1 : review.likes - 1,
            };
          } else {
            const newReplies = review.replies.map((reply) => {
              if (reply.id === replyId) {
                const liked = !reply.likedByUser;
                return {
                  ...reply,
                  likedByUser: liked,
                  likes: liked ? reply.likes + 1 : reply.likes - 1,
                };
              }
              return reply;
            });
            return { ...review, replies: newReplies };
          }
        }
        return review;
      })
    );
  };

  const addReply = (reviewId, text) => {
    if (!text.trim()) return;
    const newReply = {
      id: Date.now(),
      user: "You",
      avatar: "https://randomuser.me/api/portraits/lego/1.jpg",
      date: new Date().toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      }),
      text,
      likes: 0,
      likedByUser: false,
    };
    setReviews((prev) =>
      prev.map((review) =>
        review.id === reviewId
          ? { ...review, replies: [...review.replies, newReply] }
          : review
      )
    );
    setReplyText("");
    setReplyingTo(null);
  };

  const shareReview = (review) => {
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent(
      `Check out this review by ${review.user}: "${review.text}"`
    );
    const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${text}`;
    window.open(facebookUrl, "_blank", "width=600,height=400");
  };

  const showMore = () => {
    setVisibleCount((prev) => Math.min(prev + 2, reviews.length));
  };

  return (
    <section className="max-w-[1100px] mx-auto p-6 sm:p-10 bg-white rounded-xl shadow-lg">
      <h2 className="text-2xl font-bold mb-6 text-gray-800">Customer Reviews</h2>
      <div className="space-y-8">
        {reviews.slice(0, visibleCount).map((review) => (
          <motion.div
            key={review.id}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="bg-white rounded-lg p-6 shadow-md"
          >
            <div className="flex flex-col sm:flex-row gap-4">
              <img
                src={review.avatar}
                alt={`${review.user} avatar`}
                className="w-14 h-14 rounded-full object-cover self-start"
                loading="lazy"
              />
              <div className="flex-1">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                  <h3 className="font-semibold text-gray-800 text-lg">
                    {review.user}
                  </h3>
                  <time
                    dateTime={review.date}
                    className="text-sm text-gray-600 mt-1 sm:mt-0"
                  >
                    {review.date}
                  </time>
                </div>
                <div className="flex items-center mt-1">
                  {renderStars(review.rating)}
                </div>
                <p className="mt-3 text-gray-700 leading-relaxed whitespace-pre-wrap">
                  {review.text}
                </p>

                {/* Actions */}
                <div className="mt-4 flex flex-wrap items-center space-x-4 text-gray-600">
                  <button
                    onClick={() => toggleLike(review.id)}
                    aria-label={
                      review.likedByUser ? "Unlike review" : "Like review"
                    }
                    className="flex items-center gap-1 hover:text-amber-600 transition"
                  >
                    {review.likedByUser ? (
                      <AiFillLike className="w-5 h-5 text-amber-600" />
                    ) : (
                      <AiOutlineLike className="w-5 h-5" />
                    )}
                    <span>{review.likes}</span>
                  </button>

                  <button
                    onClick={() =>
                      setReplyingTo(replyingTo === review.id ? null : review.id)
                    }
                    aria-expanded={replyingTo === review.id}
                    aria-controls={`reply-form-${review.id}`}
                    className="hover:text-blue-500 transition font-medium"
                  >
                    Reply
                  </button>

                  <button
                    onClick={() => shareReview(review)}
                    aria-label="Share review"
                    className="hover:text-blue-500 transition flex items-center gap-1"
                  >
                    Share
                    <FaFacebookF />
                  </button>
                </div>

                {/* Reply Form */}
                <AnimatePresence>
                  {replyingTo === review.id && (
                    <motion.form
                      id={`reply-form-${review.id}`}
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.3 }}
                      onSubmit={(e) => {
                        e.preventDefault();
                        addReply(review.id, replyText);
                      }}
                      className="mt-4"
                    >
                      <textarea
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value)}
                        placeholder="Write your reply..."
                        rows={3}
                        className="w-full rounded-md border border-gray-200 p-2 text-gray-800 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
                        required
                      />
                      <div className="mt-2 flex justify-end gap-2">
                        <button
                          type="button"
                          onClick={() => {
                            setReplyingTo(null);
                            setReplyText("");
                          }}
                          className="px-4 py-2 rounded-md border border-gray-500 text-gray-700 hover:bg-gray-50 transition"
                        >
                          Cancel
                        </button>
                        <button
                          type="submit"
                          className="px-4 py-2 rounded-md bg-blue-600 text-gray-900 hover:bg-blue-700 transition"
                        >
                          Submit
                        </button>
                      </div>
                    </motion.form>
                  )}
                </AnimatePresence>

                {/* Replies */}
                {review.replies.length > 0 && (
                  <div className="mt-6 space-y-4 pl-6 border-l-2 border-gray-200">
                    {review.replies.map((reply) => (
                      <motion.div
                        key={reply.id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: 10 }}
                        transition={{ duration: 0.3 }}
                        className="flex gap-4"
                      >
                        <img
                          src={reply.avatar}
                          alt={`${reply.user} avatar`}
                          className="w-10 h-10 rounded-full object-cover self-start"
                          loading="lazy"
                        />
                        <div className="flex-1">
                          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between">
                            <h4 className="font-semibold text-gray-800 text-md">
                              {reply.user}
                            </h4>
                            <time
                              dateTime={reply.date}
                              className="text-xs text-gray-600 mt-1 sm:mt-0"
                            >
                              {reply.date}
                            </time>
                          </div>
                          <p className="mt-1 text-gray-700 leading-relaxed whitespace-pre-wrap">
                            {reply.text}
                          </p>

                          {/* Reply Like & Share */}
                          <div className="mt-2 flex items-center space-x-6 text-gray-600">
                            <button
                              onClick={() => toggleLike(review.id, reply.id)}
                              aria-label={
                                reply.likedByUser ? "Unlike reply" : "Like reply"
                              }
                              className="flex items-center gap-1 hover:text-amber-600 transition"
                            >
                              {reply.likedByUser ? (
                                <AiFillLike className="w-4 h-4 text-amber-600" />
                              ) : (
                                <AiOutlineLike className="w-4 h-4" />
                              )}
                              <span className="text-sm">{reply.likes}</span>
                            </button>
                            <button
                              onClick={() => alert("Share functionality coming soon!")}
                              aria-label="Share reply"
                              className="hover:text-blue-500 transition flex items-center gap-1 text-sm"
                            >
                              Share <FaFacebookF className="w-3 h-3" />
                            </button>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {visibleCount < reviews.length && (
        <div className="mt-8 flex justify-center">
          <button
            onClick={showMore}
            className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-gray-900 rounded-md transition"
          >
            Show More Reviews
          </button>
        </div>
      )}
    </section>
  );
};

export default ProductReviewsAdvanced;
